// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Enter your API Key',
    appId: '1:956208549258:web:e15b17081f68d51f474c73',
    messagingSenderId: '956208549258',
    projectId: 'ibas3-f5f24',
    authDomain: 'ibas3-f5f24.firebaseapp.com',
    storageBucket: 'ibas3-f5f24.appspot.com',
    measurementId: 'G-BSPSNF7NWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjon_3LA2zKghzWZ3ye9q1ORSY6Tx-iU',
    appId: '1:956208549258:android:12400938fb9dd3a9474c73',
    messagingSenderId: '956208549258',
    projectId: 'ibas3-f5f24',
    storageBucket: 'ibas3-f5f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQfUYm4a9Oc8ycFBAzNphzJ_BfEDXTlg',
    appId: '1:956208549258:ios:eac1183d221eb009474c73',
    messagingSenderId: '956208549258',
    projectId: 'ibas3-f5f24',
    storageBucket: 'ibas3-f5f24.appspot.com',
    iosBundleId: 'com.example.ibas3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQfUYm4a9Oc8ycFBAzNphzJ_BfEDXTlg',
    appId: '1:956208549258:ios:e7e51fb693ff705e474c73',
    messagingSenderId: '956208549258',
    projectId: 'ibas3-f5f24',
    storageBucket: 'ibas3-f5f24.appspot.com',
    iosBundleId: 'com.example.ibas3.RunnerTests',
  );
}
